Support non json formats + file encryption
blockstack/blockstack-ios pull request #43
Opened 2018-08-10 00:57 UTC by shreyasthiagaraj

This PR adds support for non JSON formats in getFile and putFile, specifically "text/plain" and "application/octet-stream" content types. Additionally it adds support for encryption and decryption of data.

2018-08-10 03:30 UTC, yknl reviewed
Great work! It works really well when I tried it out. Would love to see test coverage for these changes.

2018-08-13 22:29 UTC, shreyasthiagaraj commented
@yknl Submitted tests 👍🏾.

- Gaia__without_encryption__for_text_content__can_upload_and_retrieve
- Gaia__without_encryption__for_bytes_content__can_upload_and_retrieve
- Gaia__with_encryption__can_upload_and_retrieve
- Gaia__with_encryption__fails_retrieve_without_decrypt

They cover all content types (json, plain text, bytes) and encryption/no encryption cases.

2018-08-16 11:55 UTC, larrysalibra requested changes
@shreyasthiagaraj from what I can tell of the tests this seems to work. 

It would be nice if the example application was updated to demonstrate the additional functionality similar to what we have in Android.

I'd also like to see documentation of the form of api comments. For example, it's not immediately apparent from looking at the `getFile` signature how exactly one would use completion handler.

2018-08-17 10:51 UTC, shreyasthiagaraj commented
@larrysalibra done! Comments + sample app update. The sample app still needs more work to look like Android's, but that is tracked elsewhere (#46 ) and is outside the scope of this PR.

2018-08-17 12:33 UTC, larrysalibra commented on Blockstack/Classes/Blockstack.swift
> +    /**
Love these! Beautiful!

2018-08-17 12:43 UTC, larrysalibra approved these changes
This works well for me! Awesome job @shreyasthiagaraj !

2018-08-17 12:44 UTC, larrysalibra commented
I tested this out by modifying the example to store bytes instead of a string and make sure that I could read it back.

2018-08-17 12:46 UTC, merged