Profile operations
blockstack/blockstack-ios pull request #59
Opened 2018-10-05 13:41 UTC by shreyasthiagaraj

This PR adds support for the various profile-related methods, data types, and helper functions in Blockstack.js. Specific methods:

- `extractProfile`
- `wrapProfileToken`
- `signProfileToken`
- `verifyProfileToken`
- `lookupProfile`

All functions also have Objective-C bindings, found in `Blockstack+ObjC.swift`.

Thanks!
Shreyas

2018-10-11 11:20 UTC, larrysalibra requested changes
Generally looks good to me.

Couple of things:

* We shouldn't commit the  `.DS_Store` files to git.
* I'd like to see test coverage on the newly exposed profile methods. There's a test for one method, but don't see anything for the others.

2018-10-11 11:20 UTC, larrysalibra commented on Tools/Blockstack-webapp/public/redirect.html
> +  window.location="afari://?authResponse=" + authResponse
is this supposed to be here?

2018-10-22 12:49 UTC, shreyasthiagaraj commented
@larrysalibra .DS_Store files are being ignored now, and all profile methods now have tests!

2018-10-25 20:38 UTC, larrysalibra approved these changes
Thanks for the changes! I made a couple small nitpicky comments, but besides that, looks good to go!

2018-10-25 20:38 UTC, larrysalibra commented on Example/Tests/ProfileTests.swift
> +                    "exp": "2019-10-22T12:37:22.894Z",
These tests will start failing in a year - might want to make a note in a comment.

2018-10-26 12:43 UTC, merged