Network operations
blockstack/blockstack-ios pull request #82
Opened 2019-07-30 20:05 UTC by shreyasthiagaraj

This PR adds support for querying name and namespace information. Specifically, it adds support for the following methods:

- `getNameInfo`
- `getNamespaceInfo`
- `getNamePrice`
- `getNamespacePrice`

The sample app has been modified to allow playing around with this functionality, just hit the relevant buttons on screen. Thanks!!

2019-08-26 16:12 UTC, yknl requested changes
Looks like `getNamespacePrice` is not working correctly.

2019-08-26 16:12 UTC, yknl commented on Blockstack/Classes/Blockstack.swift
> +        let fetchNamePrice = Promise<[String: Any]>() { resolve, reject in
Should this be `fetchNameSpacePrice`?

2019-08-26 16:12 UTC, yknl commented on Blockstack/Classes/Blockstack.swift
> +            guard let namePrice = json["name_price"] as? [String: Any],
This always errors out because the expected JSON response is incorrect. The namespace price response from the API looks like this:
```
{
  "amount": "640000000", 
  "units": "STACKS"
}
```

2019-08-27 06:47 UTC, shreyasthiagaraj commented on Blockstack/Classes/Blockstack.swift
> +        let fetchNamePrice = Promise<[String: Any]>() { resolve, reject in
Yes it should. Fixed.

2019-08-27 08:25 UTC, shreyasthiagaraj commented on Blockstack/Classes/Blockstack.swift
> +            guard let namePrice = json["name_price"] as? [String: Any],
Fixed! I think I got this mixed up with the getNamePrice method.

2019-08-27 14:38 UTC, yknl approved these changes
Thanks, looks good now

2019-08-27 20:02 UTC, merged